Symfony/NotaResto/src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestaurantRepository::class)
 */
class Restaurant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City", inversedBy="restaurants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=RestaurantPicture::class, mappedBy="restaurant", orphanRemoval=true)
     */
    private $restaurantPictures;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="restaurant", orphanRemoval=true)
     */
    private $reviews;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="restaurants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->restaurantPictures = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|RestaurantPicture[]
     */
    public function getRestaurantPictures(): Collection
    {
        return $this->restaurantPictures;
    }

    public function addRestaurantPicture(RestaurantPicture $restaurantPicture): self
    {
        if (!$this->restaurantPictures->contains($restaurantPicture)) {
            $this->restaurantPictures[] = $restaurantPicture;
            $restaurantPicture->setRestaurant($this);
        }

        return $this;
    }

    public function removeRestaurantPicture(RestaurantPicture $restaurantPicture): self
    {
        if ($this->restaurantPictures->contains($restaurantPicture)) {
            $this->restaurantPictures->removeElement($restaurantPicture);
            // set the owning side to null (unless already changed)
            if ($restaurantPicture->getRestaurant() === $this) {
                $restaurantPicture->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setRestaurant($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getRestaurant() === $this) {
                $review->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getAverageRating()
    {
        $sum = 0;
        $total = 0;

        foreach($this->getReviews() as $review) {
            $sum += $review->getRating();
            $total++;
        }

        if ($total > 0) {
            return $sum/$total;
        }

        return null;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

Symfony/NotaResto/src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\City;
use App\Entity\Restaurant;
use App\Entity\RestaurantPicture;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class RestaurantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom du restaurant'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description du restaurant'
            ])
            ->add('created_at', DateTimeType::class,  [
                'label' => 'Date de création',
                'widget' => 'single_text',
                'input_format' => 'datetime'
            ])
            ->add('city', EntityType::class, [
                'class' => City::class,
                'choice_label' => 'name',
                'row_attr' => [
                    'class' => 'text-success font-weight-bold',
                ],
                'attr' => [
                    'class' => 'text-dark font-weight-normal restaurant-form-city'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

Symfony/NotaResto/src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Restaurant;
use App\Entity\RestaurantPicture;
use App\Entity\Review;
use App\Form\RestaurantPictureType;
use App\Form\RestaurantType;
use App\Form\ReviewType;
use App\Repository\RestaurantRepository;
use App\Service\FileUploader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/restaurant")
 */
class RestaurantController extends AbstractController
{
    /**
     * @Route("/", name="restaurant_index", methods={"GET"})
     */
    public function index(RestaurantRepository $restaurantRepository): Response
    {
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $restaurantRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="restaurant_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($restaurant);
            $entityManager->flush();

            return $this->redirectToRoute('restaurant_index');
        }

        return $this->render('restaurant/new.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{restaurant}", name="restaurant_show", methods={"GET", "POST"})
     */
    public function show(Request $request, Restaurant $restaurant, FileUploader $fileUploader): Response
    {
        /**
         * Gestion du formulaire Picture
         */
        $picture = new RestaurantPicture();
        $formPicture = $this->createForm(RestaurantPictureType::class, $picture);

        $formPicture->handleRequest($request);

        if ($formPicture->isSubmitted() && $formPicture->isValid()) {

            $file = $formPicture['filename']->getData();
            if ($file) {

                $filename = $fileUploader->upload($file);

                $picture->setFilename($filename);

                // Le restaurant de l'image est le restaurant qui est affiché sur la page
                $picture->setRestaurant($restaurant);

            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($picture);
            $entityManager->flush();

            // On redirige vers la page du restaurant une fois l'image postée
            return $this->redirectToRoute('restaurant_show', ['restaurant' => $restaurant->getId()]);
        }
        /**
         * // Fin de gestion du formulaire Picture
         */

        /**
         * Gestion du formulaire Review
         */

        $review = new Review();

        $formReview = $this->createForm(ReviewType::class, $review);
        $formReview->handleRequest($request);

        if ($formReview->isSubmitted() && $formReview->isValid()) {
            $review = $formReview->getData();

            // Le User de la review est le User connecté
            $review->setUser($this->getUser());

            // Le restaurant de la review est le Restaurant qu'on affiche
            $review->setRestaurant($restaurant);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($review);
            $entityManager->flush();

            // On redirige vers la page du restaurant une fois la review postée
            return $this->redirectToRoute('restaurant_show', ['restaurant' => $restaurant->getId()]);
        }

        /**
         * // Fin de gestion du formulaire Review
         */

        /**
         * Par défaut : on renvoie la vue restaurant/show.html.twig avec:
         * - le restaurant à afficher
         * - le formulaire d'images formPicture
         * - le formulaire de review formReview
         */
        return $this->render('restaurant/show.html.twig', [
            'restaurant' => $restaurant,
            'formPicture' => $formPicture->createView(),
            'formReview' => $formReview->createView()
        ]);
    }

    /**
     * @Route("/{restaurant}/edit", name="restaurant_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Restaurant $restaurant): Response
    {
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('restaurant_index');
        }

        return $this->render('restaurant/edit.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="restaurant_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Restaurant $restaurant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($restaurant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('restaurant_index');
    }
}

Symfony/NotaResto/templates/restaurant/_delete_form.html.twig
<form method="post" action="{{ path('restaurant_delete', {'id': restaurant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurant.id) }}">
    <button class="btn btn-secondary">Supprimer</button>
</form>

Symfony/NotaResto/templates/restaurant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}

Symfony/NotaResto/templates/restaurant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification Restaurant{% endblock %}

{% block body %}

    <div class="container-fluid">
        <a class="text-success" href="{{ path('restaurant_index') }}"><i class="fa fa-angle-double-left">  Retour</i></a>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="container text-center my-3">
                <h1>Modifier le restaurant</h1>
            </div>
            <div class="container d-flex justify-content-between">
                {{ include('restaurant/_form.html.twig', {'button_label': 'Update'}) }}
                {{ include('restaurant/_delete_form.html.twig') }}
            </div>
        </div>
    </div>

{% endblock %}

Symfony/NotaResto/templates/restaurant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurants{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="container text-center my-3">
            <h1 class="text-success">Liste de tous les restaurants</h1>
        </div>

        <div class="container">
            <a class="btn btn-outline-success mb-3" href="{{ path('restaurant_new') }}">Créer un nouveau restaurant</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nom</th>
                        <th>Ville</th>
                        <th>Note moyenne (/5)</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for restaurant in restaurants %}
                    <tr>
                        <td>{{ restaurant.id }}</td>
                        <td>{{ restaurant.name }}</td>
                        <td>{{ restaurant.city.name }}</td>
                        <td>{{ restaurant.averageRating | round(1) }}</td>
                        <td>
                            <a class="text-success mx-2" href="{{ path('restaurant_show', {'restaurant': restaurant.id}) }}"><i class="fa fa-search"></i></a>
                            <a class="text-success mx-2" href="{{ path('restaurant_edit', {'restaurant': restaurant.id}) }}"><i class="fa fa-edit"></i></a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

Symfony/NotaResto/templates/restaurant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création Restaurant{% endblock %}

{% block body %}
    <div class="container-fluid">
        <a class="text-success" href="{{ path('restaurant_index') }}"><i class="fa fa-angle-double-left">  Retour</i></a>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="container text-center my-3">
                <h1>Créer un nouveau Restaurant</h1>
            </div>
            <div class="container">
                {{ include('restaurant/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

Symfony/NotaResto/templates/restaurant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant{% endblock %}

{% block body %}
<div class="container-fluid">
    <a class="text-success" href="{{ path('restaurant_index') }}"><i class="fa fa-angle-double-left">  Retour</i></a>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="container text-center my-3">
            <h1 class="text-success">{{ restaurant.name }}</h1>
        </div>
        <div class="container">
            <div class="card mb-3">
                {% for picture in restaurant.restaurantPictures %}
                    <img src="{{ asset('/uploads/pictures/' ~ picture.filename ) }}" class="card-img-top" widht="50"alt="...">
                {% endfor %}
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <span class="font-weight-bold mr-2">Moyenne :</span>
                            {% if restaurant.averageRating is not null %}
                                {{ restaurant.averageRating | round(1) }}
                            {% else %}
                                Ce restaurant n'a pas encore de note. Soyez les premiers à laisser un avis !
                            {% endif %}
                            <span class="font-weight-bold mx-2">  / 5 </span>
                        </li>
                        <li class="list-group-item"><span class="font-weight-bold">Ville : </span><a class="text-success" href="{{ path('city_show', {'id': restaurant.city.id }) }}">{{ restaurant.city.name }}</a></li>
                        <li class="list-group-item">{{ restaurant.description }}</li>
                        <li class="list-group-item d-flex justyfy-content-between">
                            <a class="btn btn-success mr-4" href="{{ path('restaurant_edit', {'restaurant': restaurant.id}) }}">Modifier</a>
                            {{ include('restaurant/_delete_form.html.twig') }}
                        </li>
                        <li class="list-group-item">
                                Rajouter une photo :
                                {{ form_start(formPicture) }}
                                {{ form_widget(formPicture) }}
                                <button class="btn btn-sm btn-outline-success">Envoyer</button>
                                {{ form_end(formPicture) }}
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container mt-5">
            <h2>Avis sur le restaurant</h2>
            <div class="card mb-2">
                <div class="card-header">
                    Rédigez un avis sur ce restaurant !
                </div>
                <div class="card-body">
                    {{ form_start(formReview) }}
                    {{ form_widget(formReview) }}
                    <button class="btn-sm btn-outline-success float-right">Envoyer</button>
                    {{ form_end(formReview) }}
                </div>
            </div>
            <h4 class="text-success my-3">Avis laissés :</h4>
            {% for review in restaurant.reviews %}
                <div class="card mt-2">
                    <div class="card-header"><span class="badge badge-success">{{review.rating}}/5</span></div>
                    <div class="card-body">{{ review.message }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}